import 'server-only';
import { createClient, getCurrentUser } from '@/lib/supabase/server';
import { projectStatuses, projectTypes, type OrganizationOption, type ProjectListItem, type ProjectStatus, type ProjectType } from '@/types/projects';
export const pageSize = 12;
const cleanSearch = (value: string) => value.normalize('NFKC').replace(/[^\p{L}\p{N}\s-]/gu, ' ').trim().slice(0, 80);
const one = (value: string | undefined, allowed: readonly string[]) => allowed.includes(value ?? '') ? value : undefined;
export interface ProjectFilters { search: string; type?: ProjectType; status?: ProjectStatus; organization?: string; page: number; }
export function parseProjectFilters(params: Record<string, string | string[] | undefined>): ProjectFilters { const get = (key: string) => typeof params[key] === 'string' ? params[key] as string : ''; return { search: cleanSearch(get('q')), type: one(get('type'), projectTypes) as ProjectType | undefined, status: one(get('status'), projectStatuses) as ProjectStatus | undefined, organization: /^[0-9a-f-]{36}$/i.test(get('organization')) ? get('organization') : undefined, page: Math.max(1, Math.min(Number.parseInt(get('page'), 10) || 1, 10_000)) }; }
export async function getOrganizations(): Promise<OrganizationOption[]> { const user = await getCurrentUser(); if (!user) return []; const supabase = await createClient(); const { data } = await supabase.from('organization_members').select('organization_id, role, organizations(name)').eq('user_id', user.id).order('created_at'); return (data ?? []).flatMap((row) => { const org = Array.isArray(row.organizations) ? row.organizations[0] : row.organizations; return org ? [{ id: row.organization_id, name: org.name, role: row.role }] : []; }); }
export async function getProjects(filters: ProjectFilters) { const user = await getCurrentUser(); if (!user) return { projects: [] as ProjectListItem[], total: 0, error: null }; const supabase = await createClient(); let query = supabase.from('projects').select('id, name, description, type, status, organization_id, updated_at, organizations(name)', { count: 'exact' }); if (filters.search) query = query.or(`name.ilike.%${filters.search}%,description.ilike.%${filters.search}%`); if (filters.type) query = query.eq('type', filters.type); if (filters.status) query = query.eq('status', filters.status); if (filters.organization) query = query.eq('organization_id', filters.organization); const { data, count, error } = await query.order('updated_at', { ascending: false }).order('id', { ascending: false }).range((filters.page - 1) * pageSize, filters.page * pageSize - 1); if (error) return { projects: [] as ProjectListItem[], total: 0, error: 'Не удалось загрузить проекты.' }; const ids = (data ?? []).map((project) => project.id); const { data: memberships } = ids.length ? await supabase.from('project_members').select('project_id, role').eq('user_id', user.id).in('project_id', ids) : { data: [] }; const roles = new Map((memberships ?? []).map((member) => [member.project_id, member.role])); return { projects: (data ?? []).map((project) => { const org = Array.isArray(project.organizations) ? project.organizations[0] : project.organizations; return { id: project.id, name: project.name, description: project.description, type: project.type as ProjectType, status: project.status as ProjectStatus, organizationId: project.organization_id, organizationName: org?.name ?? 'Организация', updatedAt: project.updated_at, role: (roles.get(project.id) ?? null) as ProjectListItem['role'] }; }), total: count ?? 0, error: null }; }
