const productImage = './product-campaign.png';

const projects = [
  ['Забота в каждом движении', 'Рекламный ролик для NaturaCare', 'AI', '15 сентября 2026', 'Готов', 'done'],
  ['Больше, чем красота', 'Имиджевый ролик для Lumière', 'Агентство', '14 сентября 2026', 'В работе', 'work'],
  ['Пространства для жизни', 'Социальная кампания для Domus', 'AI', '12 сентября 2026', 'На проверке', 'review'],
  ['Движение вперед', 'Серия роликов для RunLab', 'Агентство', '10 сентября 2026', 'В работе', 'work'],
  ['Чистая планета', 'Ролик для Green Tomorrow', 'AI', '7 сентября 2026', 'На доработке', 'revision']
];

const navItems = [['create','Создать'],['projects','Проекты'],['team','Команда'],['media','Медиатека']];
let state = { route: 'create', query: '', type: 'Все типы', status: 'Все статусы', message: '' };

function icon(name, cls = '') {
  const chars = { search: '⌕', arrow: '→', down: '⌄', back: '←', play: '▶', volume: '◖', expand: '⛶', phone: '▯', clock: '◷', voice: '⌁', team: '♟', bolt: 'ϟ', download: '⇩', trash: '♙', comment: '●', heart: '♥', share: '◢', menu: '☰' };
  return `<span class="icon ${cls}" aria-hidden="true">${chars[name] || ''}</span>`;
}

function header(active) {
  return `<header class="topbar"><a class="brand" href="#create" aria-label="Viral Studio"><b>VIRAL</b><i>/</i><span>Studio</span><em>AI. ЛЮДИ. БОЛЬШЕ<br>ВОЗМОЖНОСТЕЙ.</em></a>
  <nav class="desktop-nav" aria-label="Основная навигация">${navItems.map(([id,label]) => `<a href="#${id}" class="${id === active ? 'active' : ''}">${label}</a>`).join('')}</nav>
  <div class="account"><button class="icon-button" data-action="search" aria-label="Поиск">${icon('search')}</button><span class="hairline"></span><a href="#profile" class="avatar black">А</a><a class="person" href="#profile"><b>Алексей</b><small>BestBite Co.</small></a><button class="chevron" data-action="toggle-menu" aria-label="Открыть меню">${icon('down')}</button><button class="mobile-menu" data-action="toggle-menu" aria-label="Меню">${icon('menu')}</button></div>
  <div class="mobile-nav" id="mobile-nav">${navItems.map(([id,label]) => `<a href="#${id}">${label}</a>`).join('')}<a href="#profile">Профиль</a></div></header>`;
}

function date() { return '<time class="date">15 сентября 2026</time>'; }
function cta(label, action, extra = '') { return `<button class="cta ${extra}" data-action="${action}"><span>${label}</span>${icon('arrow')}</button>`; }

function videoFrame({vertical = false, controls = true} = {}) {
 return `<div class="video-frame ${vertical ? 'vertical' : ''}" data-action="play-video" role="button" tabindex="0" aria-label="Воспроизвести ролик"><img src="${productImage}" alt="Косметический флакон на бежевом полотенце"><div class="video-shade"></div>${vertical ? `<p class="video-copy">Маленькие<br>ритуалы -<br>большие<br>перемены.</p><div class="socials"><b>${icon('heart')}<small>12.4K</small></b><b>${icon('comment')}<small>342</small></b><b>${icon('share')}<small>1.1K</small></b></div>` : ''}${controls ? `<div class="controls"><button aria-label="Воспроизвести">${icon('play')}</button><div class="track"><i></i></div><span>0:00 / 0:15</span>${vertical ? '' : `<button aria-label="Громкость">${icon('volume')}</button>`}<button aria-label="Развернуть">${icon('expand')}</button></div>` : ''}</div>`;
}

function createPage() { return `${header('create')}<main class="page create-page">${date()}<section class="create-grid"><div class="create-copy"><h1>ИДЕИ<br>ДВИГАЮТ<br>БИЗНЕС</h1><p>Создавайте вирусный контент с AI или заказывайте его у нашей команды.</p><div class="mode-toggle"><button class="selected" data-action="mode-ai">${icon('bolt')}Создать с AI</button><button data-action="mode-team">${icon('team')}Заказать у команды</button></div><label class="idea-box"><span class="sr-only">Идея для ролика</span><textarea data-input="idea" maxlength="500" placeholder="Опишите идею для ролика..."></textarea><small><output id="counter">0</output> / 500</small></label><div class="create-options"><button class="select-control">${icon('phone')}<span><small>Формат</small>Вертикальное 9:16</span>${icon('down')}</button><button class="select-control">${icon('clock')}<span><small>Длительность</small>15 секунд</span>${icon('down')}</button><button class="select-control">${icon('voice')}<span><small>Голос</small>Русский, нейтральный</span>${icon('down')}</button></div><div class="create-submit">${cta('Создать ролик','create-video')}<small>Быстро. Качественно. Под вашим контролем.</small></div></div><div class="create-preview">${videoFrame({vertical:true})}</div></section></main>`; }

function projectsPage() { const filtered = projects.filter(p => p[0].toLowerCase().includes(state.query.toLowerCase())); return `${header('projects')}<main class="page projects-page">${date()}<section><h1>ПРОЕКТЫ</h1><p class="subtitle">Идеи, которые двигают бизнес.</p><div class="projects-actions">${cta('Новый проект','new-project')}<div class="filter-row"><label class="search-field">${icon('search')}<input data-input="query" value="${state.query}" placeholder="Поиск по проектам..."></label>${['type','status'].map(key => `<button class="filter" data-action="filter-${key}">${state[key]} ${icon('down')}</button>`).join('')}<button class="filter" data-action="sort">По дате обновления ${icon('down')}</button></div></div><div class="project-table"><div class="project-head"><span>Проект</span><span>Тип</span><span>Обновлен</span><span>Статус</span><span></span></div>${filtered.length ? filtered.map((p,i) => `<a class="project-row" href="#media-detail"><img src="${productImage}" style="object-position:${i%2 ? '62% 34%' : '48% 58%'}" alt=""><span><b>${p[0]}</b><small>${p[1]}</small></span><span>${p[2]}</span><time>${p[3]}</time><span class="status ${p[5]}"><i></i>${p[4]}</span>${icon('arrow')}</a>`).join('') : `<p class="empty">Ничего не найдено. Попробуйте другой запрос.</p>`}</div></section></main>`; }

function teamPage() { return `${header('team')}<main class="page team-page">${date()}<section class="team-grid"><div class="team-intro"><small>AGENCY COLLABORATION</small><h1>РАБОТАЕМ<br>ВМЕСТЕ</h1><p class="case-title">BestBite -<br>Запуск линейки ухода</p><p>Вместе превращаем идеи в вирусный контент и реальные результаты.</p></div><article class="expert-card"><img src="${productImage}" alt="Мария Соколова" class="portrait woman"><span class="badge"><i></i>Назначена на проект</span><h2>Мария Соколова</h2><p>Креативный продюсер</p><hr><small>Экспертиза</small><p class="expertise">Креативные стратегии, AI-контент, продакшн, инфлюенсеры</p>${cta('Обсудить проект','discuss')}</article><section class="chat" aria-label="Переписка"><div class="chat-date">15 сентября 2026</div>${[['А','Алексей','10:24','Мария, привет! Утвердили концепцию - двигаемся к продакшну. Можешь, пожалуйста, собрать мудборд по визуальному стилю?'],['М','Мария Соколова','11:02','Привет, Алексей! Отлично, подготовлю варианты сегодня до конца дня. Учту нашу аудиторию и тональность бренда.'],['А','Алексей','12:17','Супер. Еще давай добавим идеи для рилсов и пару референсов по инфлюенсерам.'],['М','Мария Соколова','14:36','Принято! Сборка уже в работе, вышлю всё единым файлом. Если появятся комментарии - пиши, я на связи.']].map(([letter,name,time,text],i)=>`<article class="message"><span class="avatar ${i%2 ? 'image' : 'black'}">${i%2 ? '' : letter}</span><div><b>${name}</b><time>${time}</time><p>${text}</p></div></article>`).join('')}<form class="message-form" data-action="send-message"><input aria-label="Сообщение" placeholder="Напишите сообщение..." required><button class="round-button" aria-label="Отправить">${icon('arrow')}</button></form></section></section></main>`; }

function mediaDetailPage() { return `${header('media')}<main class="page media-detail">${date()}<a class="back" href="#media">${icon('back')}К медиатеке</a><section class="media-grid"><aside><h1>ВЫБРАННЫЙ<br>МАТЕРИАЛ</h1><h2>natural_care_motion_01.mp4</h2><p>Забота в каждом движении.<br>Тизер для рекламной кампании.</p><dl><div><dt>Длительность</dt><dd>00:15</dd></div><div><dt>Разрешение</dt><dd>1080 × 1920</dd></div><div><dt>Формат</dt><dd>MP4</dd></div><div><dt>Размер файла</dt><dd>24,8 МБ</dd></div><div><dt>Дата добавления</dt><dd>15 сентября 2026</dd></div></dl></aside><div class="media-player">${videoFrame()}</div><div class="thumbs">${[0,1,2,3].map((x,i)=>`<button class="thumb ${i===0 ? 'active' : ''}" data-action="thumb"><img src="${productImage}" style="object-position:${['58% 32%','48% 53%','28% 50%','75% 70%'][i]}" alt="Кадр ролика"><small>0:0${[15,7,6,8][i]}</small></button>`).join('')}</div><div class="media-actions">${cta('Добавить в проект','add-to-project')}<button data-action="download">${icon('download')}Скачать</button><button data-action="delete">${icon('trash')}Удалить</button></div></section></main>`; }

function profilePage() { return `${header('')}<main class="page profile-page">${date()}<h1>ПРОФИЛЬ</h1><section class="profile-grid"><aside class="profile-person"><img src="${productImage}" alt="Алексей" class="portrait man"><h2>Алексей</h2><p>BestBite Co.</p></aside><form class="profile-form" data-action="save-profile">${[['Имя','Алексей'],['Email','alexey@bestbite.co'],['Должность','Сооснователь']].map(([label,value])=>`<label>${label}<input value="${value}"></label>`).join('')}<button type="button" class="line-select">Язык интерфейса <b>Русский</b>${icon('down')}</button><button type="button" class="line-select">Часовой пояс <b>(GMT+03:00) Москва, Санкт-Петербург</b>${icon('down')}</button>${cta('Сохранить изменения','save-profile')}</form><section class="settings"><h2>Уведомления</h2>${[['Уведомления по email','Новости продукта, обновления и важные сообщения.',true],['Уведомления в браузере','Статусы генераций, комментарии и упоминания.',true],['Маркетинговые рассылки','Советы, кейсы и специальные предложения.',false]].map(([title,desc,on])=>`<label class="setting"><span><b>${title}</b><small>${desc}</small></span><input type="checkbox" ${on?'checked':''}><i></i></label>`).join('')}<hr><h2>Безопасность</h2><a href="#profile" data-action="password">Сменить пароль ${icon('arrow')}</a></section></section></main>`; }

function render() { const route = location.hash.slice(1) || 'create'; state.route = route; const pages = {create:createPage,projects:projectsPage,team:teamPage,media:mediaDetailPage,'media-detail':mediaDetailPage,profile:profilePage}; document.querySelector('#app').innerHTML = (pages[route] || createPage)(); }
document.addEventListener('hashchange', render);
document.addEventListener('click', e => { const link = e.target.closest('a[href^="#"]'); if (link) { e.preventDefault(); location.hash = link.getAttribute('href'); render(); } const el = e.target.closest('[data-action]'); if (!el) return; const action = el.dataset.action; if(action==='toggle-menu') document.querySelector('#mobile-nav')?.classList.toggle('open'); if(action==='new-project') { location.hash='create'; render(); } if(action==='add-to-project') { location.hash='projects'; render(); flash('Материал добавлен в проект'); } if(action==='create-video') flash('Ролик поставлен в очередь на генерацию'); if(action==='discuss') document.querySelector('.message-form input')?.focus(); if(action==='send-message') { e.preventDefault(); const input=document.querySelector('.message-form input'); if(input?.value) { flash('Сообщение отправлено'); input.value=''; }} if(action==='save-profile') {e.preventDefault(); flash('Изменения сохранены');} if(action==='download') flash('Скачивание начнется через несколько секунд'); if(action==='delete') flash('Материал перемещен в корзину'); if(action==='play-video') el.classList.toggle('playing'); if(action==='thumb') {document.querySelectorAll('.thumb').forEach(x=>x.classList.remove('active'));el.classList.add('active');} if(action?.startsWith('filter-')) { const key=action.replace('filter-',''); state[key]=state[key]==='Все типы'||state[key]==='Все статусы' ? (key==='type'?'AI':'В работе') : (key==='type'?'Все типы':'Все статусы'); render(); } });
document.addEventListener('input',e=>{if(e.target.dataset.input==='query'){state.query=e.target.value; render();} if(e.target.dataset.input==='idea') document.querySelector('#counter').textContent=e.target.value.length;});
function flash(text){let n=document.querySelector('.toast');if(!n){n=document.createElement('div');n.className='toast';document.body.append(n);}n.textContent=text;n.classList.add('show');setTimeout(()=>n.classList.remove('show'),2600);}
render();
