'use server';
import { revalidatePath } from 'next/cache';
import { createClient } from '@/lib/supabase/server';
import { projectInputSchema, type ProjectRole } from '@/types/projects';
type State = { error?: string; success?: string }; const val = (f: FormData, n: string) => String(f.get(n) ?? '');
async function auth() { const supabase = await createClient(); const { data: { user } } = await supabase.auth.getUser(); return { supabase, user }; }
async function role(projectId: string, userId: string): Promise<ProjectRole | null> { const { supabase } = await auth(); const { data } = await supabase.from('project_members').select('role').eq('project_id', projectId).eq('user_id', userId).maybeSingle(); return (data?.role ?? null) as ProjectRole | null; }
function input(form: FormData) { return projectInputSchema.safeParse({ name: val(form, 'name'), description: val(form, 'description'), type: val(form, 'type'), status: val(form, 'status'), organizationId: val(form, 'organizationId') }); }
export async function createProject(_: State, form: FormData): Promise<State> { const parsed = input(form); if (!parsed.success) return { error: 'Проверьте поля проекта.' }; const { supabase, user } = await auth(); if (!user) return { error: 'Войдите снова.' }; const { data: membership } = await supabase.from('organization_members').select('role').eq('organization_id', parsed.data.organizationId).eq('user_id', user.id).maybeSingle(); if (!membership || !['owner', 'admin'].includes(membership.role)) return { error: 'Создавать проекты могут только owner или admin организации.' }; const { error } = await supabase.from('projects').insert({ name: parsed.data.name, description: parsed.data.description, type: parsed.data.type, status: parsed.data.status, organization_id: parsed.data.organizationId, created_by: user.id }); if (error) return { error: 'Не удалось создать проект.' }; revalidatePath('/projects'); return { success: 'Проект создан.' }; }
export async function updateProject(_: State, form: FormData): Promise<State> { const parsed = input(form); const projectId = val(form, 'projectId'); if (!parsed.success || !/^[0-9a-f-]{36}$/i.test(projectId)) return { error: 'Проверьте данные проекта.' }; const { supabase, user } = await auth(); if (!user || !['owner', 'editor'].includes((await role(projectId, user.id)) ?? '')) return { error: 'У вас нет прав на изменение проекта.' }; const { error } = await supabase.from('projects').update({ name: parsed.data.name, description: parsed.data.description, type: parsed.data.type, status: parsed.data.status }).eq('id', projectId).eq('organization_id', parsed.data.organizationId); if (error) return { error: 'Не удалось обновить проект.' }; revalidatePath('/projects'); return { success: 'Проект обновлён.' }; }
export async function deleteProject(_: State, form: FormData): Promise<State> { const projectId = val(form, 'projectId'); const { supabase, user } = await auth(); if (!user || !/^[0-9a-f-]{36}$/i.test(projectId) || await role(projectId, user.id) !== 'owner') return { error: 'Удалять проект может только owner.' }; const { error } = await supabase.from('projects').delete().eq('id', projectId); if (error) return { error: 'Не удалось удалить проект.' }; revalidatePath('/projects'); return { success: 'Проект удалён.' }; }
