import { ProjectsClient } from '@/components/projects-client';
import { getOrganizations, getProjects, pageSize, parseProjectFilters, projectPageQuery } from '@/lib/projects';
import { projectStatuses, projectTypes } from '@/types/projects';
import { getCurrentProfile } from '@/lib/profile';
import { translate } from '@/lib/i18n/messages';

export default async function ProjectsPage({ searchParams }: { searchParams: Promise<Record<string, string | string[] | undefined>> }) {
  const filters = parseProjectFilters(await searchParams); const [result, organizations, profile] = await Promise.all([getProjects(filters), getOrganizations(), getCurrentProfile()]); const pages = Math.max(1, Math.ceil(result.total / pageSize)); const locale = profile?.language ?? 'ru'; const t = (key: Parameters<typeof translate>[1], vars?: Record<string, string | number>) => translate(locale, key, vars);
  return <main className="page migration-page projects-page"><small>{t('projects.eyebrow')}</small><h1>{t('projects.title')}</h1><p className="subtitle">{t('projects.subtitle')}</p><form className="project-filters" method="get"><input name="q" type="search" defaultValue={filters.search} placeholder={t('projects.search')}/><select name="type" defaultValue={filters.type??''}><option value="">{t('projects.allTypes')}</option>{projectTypes.map(x=><option value={x} key={x}>{x==='ai'?'AI':t('projects.agency')}</option>)}</select><select name="status" defaultValue={filters.status??''}><option value="">{t('projects.allStatuses')}</option>{projectStatuses.map(x=><option value={x} key={x}>{t(`projects.status.${x}` as Parameters<typeof translate>[1])}</option>)}</select><select name="organization" defaultValue={filters.organization??''}><option value="">{t('projects.allOrganizations')}</option>{organizations.map(x=><option value={x.id} key={x.id}>{x.name}</option>)}</select><button className="ghost-button">{t('common.apply')}</button></form>{result.error?<section className="projects-empty" role="alert"><h2>{t('projects.loadError')}</h2><p>{result.error}</p></section>:<><ProjectsClient projects={result.projects} organizations={organizations}/><nav className="project-pagination">{filters.page>1&&<a href={projectPageQuery(filters, filters.page - 1)}>{t('common.previous')}</a>}<span>{t('common.page',{page:filters.page,pages})}</span>{filters.page<pages&&<a href={projectPageQuery(filters, filters.page + 1)}>{t('common.next')}</a>}</nav></>}</main>;
}
